language: node_js
sudo: required
node_js:
  - 9.5.0
cache: 
  yarn: false
  directories:
    - node_modules
before_install:
  - 'npm i -g firebase-tools'
install:
  - npm install
script:
  - npm run clean:bsb
  - npm run build:bsb
  - npm run build:webpack:prod
before_deploy: "echo 'Deployment to firebase :)'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "Deployed to firebase :) !"