language: node_js
sudo: required
node_js:
  - 9.5.0
cache: 
  yarn: true
  directories:
    - node_modules
before_install:
  - 'npm i -g firebase-tools'
install:
  - yarn install
script:
  - yarn clean:bsb
  - yarn build:bsb
  - yarn build:webpack
before_deploy: "echo 'Deployment to firebase :)'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "Deployed to firebase :) !"